name: Docker Deploy Template
on:
    workflow_call:
        inputs:
            acr_name:
                description: The name of the registry
                required: true
                type: string
            image_name:
                description: The name of the image in the ACR
                required: true
                type: string
            web_app_name:
                description: The name of the Azure Web App
                required: true
                type: string
            tag:
                description: The tag for the image
                required: true
                type: string
            slot_name:
                description: The slot name where the app should be deployed
                required: false
                type: string
                default: staging
            environment:
                description: Environment this needs to be deployed on
                required: true
                type: string
            app_settings:
                description: App settings for the webapp
                required: true
                type: string


jobs:
    Deploy:
        environment: ${{inputs.environment}}
        runs-on: ubuntu-latest

        steps:
            - name: Az CLI login
              uses: azure/login@v1
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
                enable-AzPSSession: true

            - name: Whitelist IP on Webapp
              uses: azure/powershell@v1
              with:
                inlineScript: |
                    $resourcegroup = $(Get-AzWebApp -Name ${{inputs.web_app_name}}).ResourceGroup
                    $ipAddress = Invoke-RestMethod -Uri "https://api.myip.com" | Select-Object -ExpandProperty ip
                    Add-AzWebAppAccessRestrictionRule -ResourceGroupName $resourcegroup -WebAppName ${{inputs.web_app_name}} -SlotName ${{inputs.slot_name}} -Priority 300 -Action Allow -Name GithubAction -IpAddress $ipAddress/32 -TargetScmSite
                    Add-AzWebAppAccessRestrictionRule -ResourceGroupName $resourcegroup -WebAppName ${{inputs.web_app_name}} -SlotName ${{inputs.slot_name}} -Priority 300 -Action Allow -Name GithubAction -IpAddress $ipAddress/32
                azPSVersion: "latest"

            - name: Update App service settings
              uses: azure/appservice-settings@v1
              with:
                app-name: ${{inputs.web_app_name}}
                slot-name: ${{inputs.slot_name}}
                app-settings-json: ${{ inputs.app_settings }}


            - name: Deploy to Webapp
              uses: azure/webapps-deploy@v2
              with:
                app-name: ${{inputs.web_app_name}}
                publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
                images: ${{inputs.acr_name}}.azurecr.io/${{inputs.image_name}}:${{ inputs.tag }}
                slot-name: ${{inputs.slot_name}}

            - name: Sleep
              run: |
                sleep 90
            
            - name: Swap Slots
              uses: azure/powershell@v1
              with:
                inlineScript: |
                    $resourcegroup = $(Get-AzWebApp -Name ${{inputs.web_app_name}}).ResourceGroup
                    Switch-AzWebAppSlot -SourceSlotName ${{inputs.slot_name}} -DestinationSlotName Production -ResourceGroupName $resourcegroup -Name ${{inputs.web_app_name}}

                    Remove-AzWebAppAccessRestrictionRule -ResourceGroupName $resourcegroup -WebAppName ${{inputs.web_app_name}} -Name GithubAction -TargetScmSite
                    Remove-AzWebAppAccessRestrictionRule -ResourceGroupName $resourcegroup -WebAppName ${{inputs.web_app_name}} -Name GithubAction
  
                azPSVersion: "latest"
              

            - name: Azure Logout
              uses: azure/CLI@v1
              with:
                inlineScript: |
                    az logout
                    az cache purge
                    az account clear