name: Docker Deploy Template
on:
    workflow_call:
        inputs:
            acr_name:
                description: The name of the registry
                required: true
                type: string
            image_name:
                description: The name of the image in the ACR
                required: true
                type: string
            web_app_name:
                description: The name of the Azure Web App
                required: true
                type: string
            tag:
                description: The tag for the image
                required: true
                type: string


jobs:
    Deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Az CLI login
              uses: azure/login@v1
              with:
                client-id: ${{ secrets.AZURE_CLIENT_ID }}
                tenant-id: ${{ secrets.AZURE_TENANT_ID }}
                subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

            - name: Deploy to Webapp
              uses: azure/webapps-deploy@v2
              with:
                app-name: ${{inputs.web_app_name}}
                publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
                images: ${{inputs.acr_name}}.azurecr.io/${{inputs.image_name}}:${{ inputs.tag }}
                slot-name: staging

            - name: Azure Logout
              uses: azure/CLI@v1
              with:
                inlineScript: |
                    az logout
                    az cache purge
                    az account clear